version: '3.8'

services:
  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=${BACKEND_URL:-http://localhost:8000}
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - ORIGIN=http://localhost:5173
      - HOST=0.0.0.0
      - PORT=5173
      - VITE_BACKEND_URL=${BACKEND_URL:-http://localhost:8000}
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

  backend:
    image: ${BACKEND_IMAGE:-your-backend-image}
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://localhost:8000}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge 