version: '3.8'

services:
  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=https://definite-weasel-challenge-f82bb88d.koyeb.app/backend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - ORIGIN=http://localhost:5173
      - HOST=0.0.0.0
      - PORT=5173
      - VITE_BACKEND_URL=https://definite-weasel-challenge-f82bb88d.koyeb.app/backend
    depends_on:
      - backend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'

  backend:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - CUDA_VISIBLE_DEVICES=0
      - ALLOWED_ORIGINS=https://definite-weasel-challenge-f82bb88d.koyeb.app
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 160G
          cpus: '13'
    restart: unless-stopped