version: '3.8'

services:
  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./front_end:/app
      - /app/node_modules
      - /app/.svelte-kit
      - /app/build
    environment:
      - NODE_ENV=development
      - ORIGIN=http://localhost:5173
    depends_on:
      - backend

  backend:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./back_end:/app
    environment:
      - PYTHONUNBUFFERED=1