version: '3.8'

services:
  backend:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - CUDA_VISIBLE_DEVICES=0
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:5173,https://*.koyeb.app}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
      - MODEL_PATH=/app/models/ltx-video
      - BACKEND_URL=${BACKEND_URL:-http://localhost:8000}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 160G
          cpus: '13'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 