version: '3.8'

services:
  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=https://definite-weasel-challenge-f82bb88d.koyeb.app/backend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - ORIGIN=http://localhost:5173
      - HOST=0.0.0.0
      - PORT=5173
      - VITE_BACKEND_URL=https://definite-weasel-challenge-f82bb88d.koyeb.app/backend
    depends_on:
      - backend

  backend:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1