version: '3.8'

services:
  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - ORIGIN=http://localhost:5173
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s