version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '1.0'
          memory: 1G
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=768 